### PR TITLE
Add FOSSA to check licenses

### PR DESCRIPTION
**Pull request by outsideris**
### Github Issue
N/A

### Background
As we discussed last week, we need to check if we violate licenses.

### Solution
FOSSA is a service to check licenses of dependencies which we are using.
[Current report](https://app.fossa.io/projects/git%2Bgithub.com%2Fbosnet%2Fsebak) is warning there is a possibility we violate licenses. I don't know what it means yet because of I'
ve never saw this kind of violation before.

We should check how to use it.

### CODE REVIEW

**Comment by Geod24** [comment]
I went through our deps.
You can check compatibility with https://www.gnu.org/licenses/license-list.en.html (that's the official FSF advice, written by rms).
We use GPL v3

MIT ✅ (https://www.gnu.org/licenses/license-list.en.html#Expat) :
- https://github.com/GianlucaGuarini/go-observable/blob/master/LICENSE
- https://github.com/beorn7/perks/blob/master/LICENSE
- https://github.com/mattn/go-colorable/blob/master/LICENSE 
- https://github.com/mattn/go-isatty/blob/master/LICENSE 
- https://github.com/go-stack/stack/blob/master/LICENSE.md 
- https://github.com/hpcloud/tail/blob/master/LICENSE.txt 
- https://github.com/onsi/ginkgo/blob/master/LICENSE 
- https://github.com/onsi/gomega/blob/master/LICENSE
- https://github.com/satori/go.uuid/blob/master/LICENSE
- https://github.com/lib/pq/blob/master/LICENSE.md
- https://github.com/stretchr/testify/blob/master/LICENSE

BSD-3 ✅ (https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD) :
- Golang: https://github.com/golang/go/blob/master/LICENSE
- https://github.com/agl/ed25519/blob/master/LICENSE
- https://github.com/fsnotify/fsnotify/blob/master/LICENSE
- https://github.com/golang/protobuf/blob/master/LICENSE
- https://github.com/golang/snappy/blob/master/LICENSE
- https://github.com/google/uuid/blob/master/LICENSE
- https://github.com/gorilla/context/blob/master/LICENSE
- https://github.com/gorilla/mux/blob/master/LICENSE
- https://github.com/pmezard/go-difflib/blob/master/LICENSE
- https://github.com/spf13/pflag/blob/master/LICENSE
- https://github.com/pmezard/go-difflib/blob/master/LICENSE

BSD-2 ✅ (https://www.gnu.org/licenses/license-list.en.html#FreeBSD):
- https://github.com/gorilla/handlers/blob/master/LICENSE
- https://github.com/pkg/errors/blob/master/LICENSE
- https://github.com/syndtr/goleveldb/blob/master/LICENSE

ISC ✅ (https://www.gnu.org/licenses/license-list.en.html#ISC) :
- https://github.com/btcsuite/btcd/blob/master/LICENSE 
- https://github.com/btcsuite/btcutil/blob/master/LICENSE 
- https://github.com/davecgh/go-spew/blob/master/LICENSE 
- https://github.com/nullstyle/go-xdr/blob/master/LICENSE

LGPLv3 ✅ (https://www.gnu.org/licenses/license-list.en.html#LGPLv3) :
- https://github.com/ethereum/go-ethereum/blob/master/COPYING

Apache 2 ✅ (https://www.gnu.org/licenses/license-list.en.html#apache2):
- https://github.com/inconshreveable/log15/blob/master/LICENSE
- https://github.com/inconshreveable/mousetrap/blob/master/LICENSE
- https://github.com/matttproud/golang_protobuf_extensions/blob/master/LICENSE
- https://github.com/oklog/run/blob/master/LICENSE
- https://github.com/prometheus/client_golang/blob/master/LICENSE
- https://github.com/prometheus/client_model/blob/master/LICENSE
- https://github.com/spf13/cobra/blob/master/LICENSE.txt
- https://github.com/stellar/go/blob/master/LICENSE-APACHE.txt

We're all good here. I think the warnings in FOSSA might be triggered by certain licenses being unrecognized.

**Comment by outsideris** [comment]
I changed the license policy from `Single-Binary Distribution` to `Standard Bundle DIstribution`.
Then I reviewed and resolved them(including AGPL, GPL MS-RL) because of we disclosed our source code.

**Comment by Geod24** [comment]
Shall we merge ?

**Comment by anarcher** [comment]
Can I merge it? @outsideris  :-)

**Pull request merged**
