### PR TITLE
Write API blueprint 

### PR DESCRIPTION
**Pull request by anarcher**
### Github Issue

#274 

### Background

Using api-buleprint

### Solution

#314

### Possible Drawbacks

After this PR, This doc should check about information and English with @cmcm2222

### CODE REVIEW

**Comment by outsideris** [comment]
Can you rebase?

**Comment by anarcher** [comment]
@outsideris @kfangw I don't know how to show field description with api blueprint.

```

**Comment by anarcher** [comment]
@outsideris I did rebase! :-D

**Comment by anarcher** [comment]
https://www.npmjs.com/package/json-schema-view-js lt is a render of json schema

**Pull request merged**
