### PR TITLE
Fix CI: Comment out flakey test + revert #340

### PR DESCRIPTION
**Pull request by Geod24**
It keeps on triggering 'Negative WaitGroup counter' and is hindering development.

### CODE REVIEW

**Comment by Geod24** [comment]
Wait the integration tests are failing. That's no good...

Also:
> --- FAIL: TestNodeRunnerCreateAccount (6.51s)
>     node_runner_test.go:250: failed to broadcast message node GAHJ.D5YP index 1

**Comment by Charleslee522** [comment]
@Geod24 It's not related with #340 :)
> node_runner_test.go:250: failed to broadcast message node GAHJ.D5YP index 1

I remember that this error occurred sometimes before #340.

**Comment by Geod24** [comment]
@Charleslee522 : #340 broke the integration tests. This is fairly obvious if you look [here](https://github.com/bosnet/sebak/commits/master). The commit before #340 passed the integration test, and #340 didn't.
Since the integration tests are E2E tests, they do not suffer from the same bug we see in the unittests. They have never been spurious.

**Comment by Charleslee522** [comment]
I just wrote about unittest `TestNodeRunnerCreateAccount`

@Geod24 How can I check the result of E2E test? :)

**Pull request merged**
