### PR TITLE
Sync 

### PR DESCRIPTION
**Pull request by anarcher**
### Github Issue

Related: #302

### Background

IMHO, This is a much more`* N` simple version of sync than #448  `~_~`

### Solution

- Just use `WorkerPool` for syncing. (default pool size is 300)

```
func (s *Syncer) work(height uint64) {
	ctx := s.ctx
	work := func() {
	L:
		for {
			select {
			case <-ctx.Done():
				break L
			default:
				currHeight := s.currBlockHeight()
				if currHeight > 0 && height <= currHeight {
					s.logger.Info("This height has already synced", "height", height)
					break L
				}
				blockInfo, _ := s.fetcher.Fetch(ctx, height)
				if err := s.validator.Validate(ctx, blockInfo); err != nil {
					s.logger.Error("validate failure", "err", err)
					continue
				}
				break L
			}
		}
		s.logger.Info("Done sync", "height", height)
	}
	s.workPool.Add(ctx, work)
}
```

- If Fetcher and Validator need to do work concurrently, They can have their own `WorkerPool` too. `'ㅅ'`

### CODE REVIEW

**Comment by spikeekips** [comment]
❤️

**Comment by Charleslee522** [comment]
@anarcher Is this in progress yet? :)

**Comment by anarcher** [comment]
Not yet ㅠㅠ. I think that it’s time to talk how do interacting with consensus module with syncer :)

**Comment by anarcher** [comment]
```
type SyncProgress struct {
    HighestBlock uint64 // Highest alleged block number in the chain
    CurrentBlock uint64 // Current block number where sync is at
    LastestBlock uint64 // Lastest block number which is saved in the node.
}

type SyncProgressHandler interface {
    SyncProgress(context.Context) (*SyncProgress, error)
    SetSyncTargetBlock(ctx context.Context, height uint64) error
}
```

**Pull request merged**
