### PR TITLE
modify blockOperation

### PR DESCRIPTION
**Pull request by soonkuk**
### Background
This PR is made to resolve frozen account issue.
The problem was that `/accounts/{addr}/frozen-accounts` return no records even if creating frozen accounts are a success.

### CODE REVIEW

**Comment by outsideris** [comment]
To keep history, the problem was that `/accounts/{addr}/frozen-accounts` return no records even if creating frozen accounts are a success.

**Comment by soonkuk** [comment]
@outsideris Ok I will add it to the background

**Comment by outsideris** [comment]
On my local test, it works correctly.
I have questions. If i had frozen accounts already before this PR, they are not returened. Right? 
Only new frozen accounts are returned after this PR.

**Comment by soonkuk** [comment]
@outsideris Yes that was not saved.

**Comment by kfangw** [comment]
@soonkuk integration_tests_sdk  failed occasionally.
I will investigate this. Please rerun until succeed.
And I will make an integration test for this case soon.

**Comment by soonkuk** [comment]
@kfangw Ok I got it.

**Pull request merged**
