### PR TITLE
Using API blueprint for API document

### PR DESCRIPTION
**Pull request by outsideris**
### Github Issue
Related to #274

### Background
It's another approach for API document which is different with #300 . 
[API blueprint](https://apiblueprint.org/) is API document format.

### Pros
* API blueprint is compatible with markdown. So, it's human-readable in GitHub before generating HTML.
* It doesn't disrupt our source code. API document needs much text. I dislike too many comments above the source code.

### Cons
* We should care about API document. Because it is not generated from our source. We should write them. Otherwise, it will be outdated quickly.
* Default theme is not so good even though we can customize it.
* There is no "Try it out" feature.

### CODE REVIEW

**Comment by outsideris** [comment]
Additionally, we can prevent our document is outdated if we use [dredd](https://dredd.readthedocs.io/en/latest/).

Dredd is API test framework. It will run test based on API blueprint document: 



Dredd uses our parameter example and response. So, if we change our API but, document doesn't changed, test will be fail.

However, we should write our document strictly to use dredd. Because all example on the document should be real test data.

**Comment by anarcher** [comment]
I like this approach of api blueprint.  And `github.com/swaggo/swag` doesn't support multiple descriptions not yet..

**Comment by anarcher** [comment]
Can we use the `dredd` with CI?

**Comment by cmcm2222** [comment]
Sorry for late review. 
Thanks for kind explanation. @outsideris 
LGTM

**Pull request merged**
