### PR TITLE
#60 Fixed checkpoint validation

### PR DESCRIPTION
**Pull request by spikeekips**
### Github Issue
Please see #60.

### CODE REVIEW

**Comment by cmcm2222** [comment]
@Geod24 this pr should be reviewed faster. right??

**Comment by spikeekips** [comment]
@Geod24 and @cmcm2222 Yes, please pay attention to this :)

**Comment by outsideris** [comment]
This PR has a broken link to forked branch.
I think we should close it and reopen it.

**Comment by spikeekips** [comment]
@outsideris ㅠㅠㅠㅠ yeah, so sad. I will check.

**Comment by spikeekips** [comment]
As @outsideris pointed, this PR was disconnected with the original forked repo, so new PR, #88  was pushed.

**Pull request closed without merging**
