### PR TITLE
Change CongressVoting's Contract field type from []byte to string

### PR DESCRIPTION
**Pull request by kfangw**
### Background
To improve the usability of client-side,
[]byte is changed to string

### CODE REVIEW

**Comment by zzim2x** [comment]
LGTM!!

**Comment by Geod24** [comment]
1) Would be better to give a more useful name to the commit / PR. E.g. "Change CongressVoting.Contract type to string". We have [guidelines](https://github.com/bosnet/sebak/blob/13dbe0a17626858b51b61b4dde078554b5597458/CONTRIBUTING.md#pull-request) which reference [7 great rules to write a commit message](https://chris.beams.io/posts/git-commit/)
2) What is the content of `Contract` supposed to be ? I thought that it would be bytecode ?

**Comment by outsideris** [comment]
It passed signature validation.

The response is `submitted` when I send a tx for congress voting

```
{ _links:
   { history:
      { href:
         '/api/v1/transactions/ADKdkaDm1Qcy3Jy7w4YzuyiZ6CwabN9BKdaqBdDNTaXL/history' },
     self: { href: '/api/v1/transactions' } },
  hash: 'ADKdkaDm1Qcy3Jy7w4YzuyiZ6CwabN9BKdaqBdDNTaXL',
  message:
   { source: 'GCT67AX6PSARM47MJYAEMAQTS4LQRJDJFSMBAEEKHVCDIP5VRC3P2RPC',
     fee: '10000',
     sequence_id: 0,
     operations: [ [Object] ] },
  status: 'submitted' }
```

However, the transaction status is `rejected`.

```
curl --insecure https://localhost:12345/api/v1/transactions/ADKdkaDm1Qcy3Jy7w4YzuyiZ6CwabN9BKdaqBdDNTaXL/history | jq .
{
  "_links": {
    "account": {
      "href": "/api/v1/accounts/GCT67AX6PSARM47MJYAEMAQTS4LQRJDJFSMBAEEKHVCDIP5VRC3P2RPC"
    },
    "self": {
      "href": "/api/v1/transactions"
    },
    "transaction": {
      "href": "/api/v1/transactions/ADKdkaDm1Qcy3Jy7w4YzuyiZ6CwabN9BKdaqBdDNTaXL"
    }
  },
  "confirmed": "2018-11-19T16:14:32.748815000+09:00",
  "created": "2018-11-19T16:14:32.735000000+09:00",
  "hash": "ADKdkaDm1Qcy3Jy7w4YzuyiZ6CwabN9BKdaqBdDNTaXL",
  "source": "GCT67AX6PSARM47MJYAEMAQTS4LQRJDJFSMBAEEKHVCDIP5VRC3P2RPC",
  "status": "rejected"
}
```

**Comment by Geod24** [comment]
@outsideris : The question is: "Is that field supposed to be string, or byte code?".
If it's supposed to be string, it LGTM. But I thought it was supposed to be bytecode and we just use strings for testing.

**Comment by outsideris** [comment]
> For transfer that's fine, but if we store it this way, it means a 33% overhead.

In this aspect, the interface for RLP should be string at least. We can't separate both things?

**Comment by Geod24** [comment]
I would like to have them separated, but at the moment we don't (e.g. we save in JSON)

**Comment by outsideris** [comment]
I think we can merge this because `rejected` case is open in #757 
And separating RLP data type and database data type can be handled in another issue. 
How do you think? @Geod24

**Comment by outsideris** [comment]
Tests should be passed, of course. :)

**Pull request merged**
