### PR TITLE
Fix issue 395: Drop support for Go v1.10

### PR DESCRIPTION
**Pull request by Geod24**
Just leaving this here, for when the team think it's ready.

### CODE REVIEW

**Comment by anarcher** [comment]
If you want to use go module, you can use `vgo` with go 1.10 (maybe?). 
- https://github.com/golang/vgo

**Comment by Geod24** [comment]
@outsideris : Could you disable "Required" on `ci/circleci: test_go1_10` then ?

**Comment by anarcher** [comment]
IMHO, I would like to wait to `go.1.11.x` . `go1.11` probably has some issues.  ㅋㅋ

**Comment by outsideris** [comment]
I disabled go1.10 required

**Comment by Geod24** [comment]
> IMHO, I would like to wait to `go.1.11.x` . `go1.11` probably has some issues. ㅋㅋ

[Here you go](https://groups.google.com/forum/#!topic/golang-announce/pFXKAfoVJqw)

**Comment by Geod24** [comment]
Actually, it looks like we haven't been running the unittests with v1.10 for a while, since it was using `defaults`, and `defaults` was updated to Go v1.11 🙈

**Comment by Geod24** [comment]
@spikeekips : I don't see anything in the README that needs an update.

**Comment by spikeekips** [comment]
@Geod24 I was confused, I want to say, installation doc in wiki, https://github.com/bosnet/sebak/wiki/SEBAK-Installation-Guide . There are `dep` related things.

**Comment by Geod24** [comment]
@spikeekips : Shouldn't this happen after this PR is merged then ?

**Comment by spikeekips** [comment]
@Geod24 👍

**Comment by Geod24** [comment]
I'm going to merge this now, without the switch to Go modules, because it will already help our CI, which is overloaded. I'll submit another PR for the switch to Go modules.

**Pull request merged**
