### PR TITLE
 `/api/v1/account` to `/api/v1/accounts`

### PR DESCRIPTION
**Pull request by anarcher**
### Solution

Change the URL  `/api/v1/account` to `/api/v1/accounts`

### CODE REVIEW

**Comment by kfangw** [comment]
I want you to add one more if you agreed
```/api/v1/accounts```
How about follows the REST even if we don't have API for the accounts without id?

**Comment by Geod24** [comment]
@anarcher : Can you add an integration test for the payment ?

**Comment by anarcher** [comment]
@Geod24 I changed integration test  with `/api/v1/account` haha...;ㅁ;
@kfangw Oh We will change to `/api/v1/accounts`?

**Comment by kfangw** [comment]
yes please :)

**Comment by anarcher** [comment]
I will change the PR for `/api/v1/accounts`

**Comment by anarcher** [comment]
@kfangw @outsideris @Geod24 I changed the URLs :->

**Pull request merged**
