### PR TITLE
Merge new-proposer into master

### PR DESCRIPTION
**Pull request by Geod24**
Merge `new-proposer` into `master`

### CODE REVIEW

**Comment by Geod24** [comment]
@spikeekips @Charleslee522 : Once I get your approval I'll push to master.
I suggest not to merge any PR in master in the meantime to avoid conflicts.

**Comment by Charleslee522** [comment]
Are you waiting for @spikeekips ? :)

**Comment by Geod24** [comment]
Yes :)

**Comment by Geod24** [comment]
Blocked since #325 broke this.
The simplest solution would be to revert #325 and merge this. Otherwise we'll have to go through the merge/review process again. Any idea @Charleslee522 @spikeekips ?

**Comment by Charleslee522** [comment]
@Geod24 How about just adding new commit for resolving conflict `lib/api_test.go`? Any problem?

**Comment by Geod24** [comment]
@Charleslee522 : Merges of branches are not handled as normal PR because it would create double merge commits which just adds noise, and squashing / rebase is not an option.
So the only option is to redo from start.

**Comment by Charleslee522** [comment]
@Geod24 Ok, then if @kfangw doesn't mind, revert #325 -> merge this -> apply #325.

**Comment by kfangw** [comment]
@Geod24 @Charleslee522 I don't mind that revert the commit.
BTW, If there is a branch rebase/merge issue, make an announcement on slack.
If I know the issue, I wouldn't merge that branch.

**Pull request merged**
