### PR TITLE
Add verbose and dry run mode to sebak wallet pay

### PR DESCRIPTION
**Pull request by Geod24**
```
This will allow people to create test cases for our integration test suite more easily.
```

E.g. look at the JSON files in #188

### CODE REVIEW

**Comment by outsideris** [comment]
Do you want to comapre with printed output in tests?

**Comment by Geod24** [comment]
At the moment the tests don't allow us to do that. Also, the testsuite as designed in #188 is not intended to test the CLI interface (although it would be possible), but focuses on the `node`, which is IMO the most important part ATM.

**Comment by Geod24** [comment]
In fact, after implementing another test, I think it would be beneficial to also add a verbose option which both sends the request and prints it.

**Comment by Geod24** [comment]
@outsideris : I forgot to push the verbose flag originally. Can you give it a second look ?

**Comment by outsideris** [comment]
Why not. Looks good.

**Pull request merged**
