### PR TITLE
Using storage/statedb with contract

### PR DESCRIPTION
**Pull request by anarcher**
- Fix to move Amount to sebakcommon.Amount, Merge storage/statedb
- Using storage/statedb with contract

### CODE REVIEW

**Comment by Geod24** [comment]
I would encourage you to rebase your branch on master instead of merging master into it.

**Comment by kfangw** [comment]
@Geod24 @anarcher I rebased the bosnet:contract_stateclone branch on current master

**Comment by kfangw** [comment]
Is StateDB used only for keys not for cache?

**Comment by anarcher** [comment]
- https://github.com/bosnet/sebak/pull/236
- https://github.com/bosnet/sebak/pull/236/files#diff-d1cfedff8f590c61b84a2a35218a88e4R77

`StateDB` uses `LevelDB’s Transaction` for cache layer for now.

**Comment by anarcher** [comment]
@kfangw Thanks for rebase! :-)

**Comment by anarcher** [comment]
Can I merge this PR to `contract-stateclone` branch? @kfangw 

About cache layer in statedb, I will consider antoher approach such as state_object or something else if this current approach doesn’t works well.

**Comment by kfangw** [comment]
@anarcher It is good to be merged
I am trying to attach the statedb into the consensus. It seems ok until now.

**Comment by anarcher** [comment]
When the statobject uses within DbBackend.Get , may be we should use refleact pkg for it

**Pull request merged**
