### PR TITLE
add condition ratio for ricardian contract sample

### PR DESCRIPTION
**Pull request by outsideris**
* add `execution_condition_ratio` to calculate final voting result. This field is treated as required field in voting server.
* remove new line for print user screens which has vary width.

### CODE REVIEW

**Comment by Geod24** [comment]
Do we have any formal documentation for those fields ?

**Comment by soonkuk** [comment]
@Geod24 @spikeekips 
execution_condition_ratio : The execution_ratio is used to determine the voting threshold in execution condition. The voting threshold is calculated by the execution_ration of the number of members as of end of voting.

execution_condition:
    Membership reward PF Proposal will be regarded as being approved by Congress Members via Congress Voting if the following condition is met;
      - A - B ≥ C × 0.1
      - A = the number of "Agree" votes.
      - B = the number of "Disagree" votes.
      - C = the number of Members as of end of voting.

**Comment by spikeekips** [comment]
@soonkuk I got it and please add this definition to https://github.com/bosnet/docs/issues/1 .

**Comment by soonkuk** [comment]
@spikeekips Ok I will add it.

**Comment by spikeekips** [comment]
@outsideris Please merge~

**Pull request merged**
