### PR TITLE
Improve TestBlockHeightOrdering

### PR DESCRIPTION
**Pull request by Geod24**
This test checks for an impossible scenario: blocks being saved out of order.
It's not something that should ever happen, and if anything, this test should not pass.

### CODE REVIEW

**Comment by spikeekips** [comment]
@Geod24 This test is for checking `GetBlockByHeight()`, so 'ordering' means `GetBlockByHeight()` gets `Block` by `Block.Height`. The name of function maybe mislead the purpose.

**Comment by Geod24** [comment]
@spikeekips : Following your comment, I updated the test to do just that.

**Comment by spikeekips** [comment]
Test passes, I will approve.

**Comment by Geod24** [comment]
Fixed the format issue

**Pull request merged**
