### PR TITLE
Make new-proposer compile

### PR DESCRIPTION
**Pull request by Geod24**
@spikeekips : This is the bare minimum required to make `new-proposer` compile.
I suggest we merge this and then discuss if we need a second threshold (or a configurable threshold at all) so that people can work on the branch. What do you think ?

### CODE REVIEW

**Comment by Geod24** [comment]
Alright we need https://github.com/bosnet/sebak/pull/248/commits/36be761f2587679d8dde98377f396ce8fb3e1dce for tests to pass, which is why I recommended to put it in master (it makes sense on its own anyway).

**Comment by spikeekips** [comment]
@Geod24 Except 36be761, we already started review for #240. I think we can wrap up ASAP including threshold(s) :) Anyway I will submit new PR for 36be761.

**Comment by spikeekips** [comment]
#253 submitted.

**Comment by Geod24** [comment]
@spikeekips : Except that there is some discussion happening in #240 
I don't think we should tie the outcome of those discussions to the ability of our whole team to work on new-proposer when we have such a trivial fix easily available.

**Comment by spikeekips** [comment]
@Geod24 I don't understand why you make this PR instead of trying to finish #240. As you know, #240  is the first and main PR, `new-propser` branch is just branch. If we can finish #240, the `new-proposer-bug-fixes` will be merged, not `new-propser`.

**Comment by Geod24** [comment]
@spikeekips : The point was not to block people on the outcome of #240 
Since the second threshold option is controversial, I suggested to fix the current bugs but keep the same behavior, and not block it on the additional code you want to introduce.

**Comment by Geod24** [comment]
#240 was merged

**Pull request closed without merging**
